on:
  push:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: 
    steps:
      - uses: actions/checkout@v3
      - uses: ./
      - run: firebase --version
